[package]
name = "fluss"
version = "0.1.0"
authors = ["Mahmut Bulut <vertexclique@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
futures-preview = "0.3.0-alpha.17"
pin-utils = "0.1.0-alpha.4"
slab = "0.4.2"

[dev-dependencies]
async-std = "0.99"
