name: Rust MacOS

on: [push]

jobs:
  build:
    container: rustlang/rust:nightly-slim

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        rust: [nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
